In [1]:
2>1

True

In [2]:
import numpy as np

# Create a new salaries array
salaries2019 = [20000, 25000, 30000, 35000, 40000, 450000, 50000]

new_salaries = np.array(salaries2019)

# Use greater than to find all salaries above 35000
big_salaries = new_salaries > 35000

print(big_salaries)

[False False False False  True  True  True]


In [3]:
import numpy as np

store_1_sales = (1200,1400,1000,900)
np_store_1_sales = np.array(store_1_sales)

store_2_sales = (1000,1700,1050,1600)
np_store_2_sales = np.array(store_2_sales)

average_sales = 1300

print(np_store_1_sales > average_sales)
print(np_store_2_sales > average_sales)


[False  True False False]
[False  True False  True]


In [4]:
np_store_1_sales >np_store_2_sales

array([ True, False, False, False])

In [5]:
import numpy as np

store_3_sales = (200,800,750,900)
np_store_3_sales = np.array(store_3_sales)

#find sales greater than 600
np_store_3_sales > 600

array([False,  True,  True,  True])

In [7]:
daily_average_sales = 800
np_store_3_sales < daily_average_sales


array([ True, False,  True, False])

In [8]:
np_store_3_sales >= 0 and np_store_3_sales <= 500


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
np.logical_and(np_store_3_sales >= 0, np_store_3_sales <= 500
)

array([ True, False, False, False])

In [12]:
#select figure
np_store_3_sales[np.logical_and(np_store_3_sales >= 0,np_store_3_sales<=500)]

array([200])

In [25]:
name = "mjay"
if name == "Mjay":
    print("Hello Mjay!")
elif name == "mjay":
    print("Hello Mjay")
else:
    print("you are not mjay you cant log in")

Hello Mjay


In [29]:
#Filtering Data frames
import pandas as pd

#import our speaks english file
speaks_english = pd.read_csv("datasets/speaks_english.csv", index_col =0
)

#print 
speaks_english


country  speaks_english  2015 population
IE         ireland            True              4.7
UK  united kingdom            True             65.3
DE         germany           False             81.7
FR          france           False             64.4
AU       australia            True             23.8
US   united states            True            319.9
JP           japan           False            129.9

In [30]:
speaks_english["2015 population"]

IE      4.7
UK     65.3
DE     81.7
FR     64.4
AU     23.8
US    319.9
JP    129.9
Name: 2015 population, dtype: float64

In [31]:
speaks_english["2015 population"]>60

IE    False
UK     True
DE     True
FR     True
AU    False
US     True
JP     True
Name: 2015 population, dtype: bool

In [32]:
over_60 =speaks_english["2015 population"]>60

In [33]:
speaks_english[over_60]

country  speaks_english  2015 population
UK  united kingdom            True             65.3
DE         germany           False             81.7
FR          france           False             64.4
US   united states            True            319.9
JP           japan           False            129.9

In [34]:
speaks_english[speaks_english["2015 population"]>60]

country  speaks_english  2015 population
UK  united kingdom            True             65.3
DE         germany           False             81.7
FR          france           False             64.4
US   united states            True            319.9
JP           japan           False            129.9

In [38]:
import numpy as np

np.logical_and(speaks_english["2015 population"] > 60, speaks_english["2015 population"] < 100)


IE    False
UK     True
DE     True
FR     True
AU    False
US    False
JP    False
Name: 2015 population, dtype: bool

In [39]:
speaks_english[np.logical_and(speaks_english["2015 population"] > 60, speaks_english["2015 population"] < 100)]

country  speaks_english  2015 population
UK  united kingdom            True             65.3
DE         germany           False             81.7
FR          france           False             64.4