In [14]:
#creatre a new list of employee salary
#use python function max() to find the max salary in the list
employees = [20000,300000,53699,346333,4567]
max(employees)

346333

In [15]:
#create a new variable;highest paid
highest_paid = max(employees)

#output highest paid
highest_paid

346333

In [1]:
#use round() to round to 2 decimal places
pi = round(3.1419265358979,2)

#print pi
pi

3.14

In [2]:
#round 1.68 to 1 dp
num = round(1.68,1)
#num01 = round(1.68)
#print num
num
#num01

1.7

In [3]:
#create two new lists of employee salary
developers = [2345,23456,567654,54678,534213,8763,98743]
testers = [25000,30000]

#combine both lists
technical_team_salary = developers + testers

#print combined lists
print(technical_team_salary)

[2345, 23456, 567654, 54678, 534213, 8763, 98743, 25000, 30000]


In [ ]:
help(sorted)

In [6]:
#list with argument reverse = True
technical_team_salary_sorted = sorted(technical_team_salary, reverse = True)

#output new lists
print(technical_team_salary_sorted)

[567654, 534213, 98743, 54678, 30000, 25000, 23456, 8763, 2345]


In [7]:
technical_team_salary_sorted = sorted(technical_team_salary)
print(technical_team_salary_sorted)


[2345, 8763, 23456, 25000, 30000, 54678, 98743, 534213, 567654]


In [8]:
len(technical_team_salary)

9

In [9]:
#capitalize() as a method
lead_developer = 'marv'


In [10]:
lead_developer.capitalize()

'Marv'

In [11]:
#replace
lead_developer.replace("v","o")

'maro'

In [18]:
developers = [30000,35000,40000,45000,50000,55000]

#apply .append() method to developers list with one argument
developers.append(70000)

#output developers
#print(developers)
developers

[30000, 35000, 40000, 45000, 50000, 55000, 70000]

In [19]:
#IMPORT THE NumPy package
import numpy

In [20]:
#this approach wont work
#new_array = array([1,2,3])

In [21]:
new_array = numpy.array([1,2,3])
new_array

array([1, 2, 3])

In [22]:
#preffered option
import numpy as np
array2 = np.array([1,2,3])
array2

array([1, 2, 3])

In [23]:
from numpy import array
array3 = array([1,2,3])

In [24]:
array3

array([1, 2, 3])